openapi: 3.1.0

info:
  title: Postcrunch
  description: 'A social media platform where we crunch others post and share ours.'
  version: 1.0.0
  contact:
    name: Nguyen Pham
    email: nguyenminhpham24@gmail.com

servers:
  - url: https://github.com/nguyepham
    description: Development server

tags:
  - name: user
    description: Everything about users and accounts.
  - name: newsfeed
    description: CRUD operations with the newsfeed.
  - name: post
    description: CRUD operations with a post.
  - name: comment
    description: CRUD operations with a comment.
  - name: vote
    description: CRUD operations with a vote.
  - name: report
    description: CRUD operations with a report.

paths:

  /api/v1/posts/{id}:
    get:
      tags:
        - post
      description: Get a post's details.
      operationId: getPostById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Fetch successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/InternalServerError'

components:

  responses:
    BadRequest:
      description: There are problems with the request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    Unauthorized:
      description: Access token is missing or invalid.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    NotFound:
      description: The requested resources not found.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    InternalServerError:
      description: An unexpected error occurred on the server.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

  schemas:
    User:
      type: object
      description: A Postcrunch user.
      required:
        - username
        - password
      properties:
        id:
          type: string
          description: The user's id.
        username:
          type: string
          description: The account's username used as the default display name.
        password:
          type: string
          description: The account's password.
        first_name:
          type: string
          description: The display name of the user.
        last_name:
          type: string
          description: The display name of the user.
        email:
          type: string
          description: The user's email.
          format: email
        dob:
          type: string
          description: The user's birthday.
          format: date-time
        gender:
          type: string
          description: The user's gender.
        contents:
          type: array
          description: The list of contents created by the user.
          items:
            type: string
            description: The id of the content created by the user.
        votes:
          type: array
          description: The list of votes created by the user.
          items:
            type: string
            description: The id of the vote created by the user.
        report:
          type: array
          description: The list of reports created by the user.
          items:
            type: string
            description: The id of the report created by the user.

    Newsfeed:
      type: object
      description: The Postcrunch newsfeed.
      properties:
        posts:
          type: array
          description: The list of posts on the newsfeed.
          items:
            type: string
            description: The id of the post in the list.
        comments:
          type: array
          description: The list of comments on the newsfeed.
          items:
            type: string
            description: The id of the comment in the list.

    NewContent:
      type: object
      required:
        - contentType
      properties:
        contentType:
          type: string
          description: The type of this content.
          enum:
            - POST
            - COMMENT
        text:
          type: string
          description: The text in the content.

    AddPostReq:
      allOf:
        - $ref: '#/components/schemas/NewContent'
        - type: object
          properties:
            authorId:
              type: string
              description: Info about the post's author wrapped in the request.

    AddCommentReq:
      allOf:
        - $ref: '#/components/schemas/NewContent'
        - type: object
          properties:
            authorId:
              type: string
              description: Info about the comment's author wrapped in the request.
            targetId:
              type: string
              description: Info about the comment's target wrapped in the request.

    Content:
      allOf:
        - $ref: '#/components/schemas/NewContent'
        - type: object
          description: A content on the newsfeed (post or comment).
          properties:
            id:
              type: string
              description: The content's id.
            createdAt:
              type: string
              description: The time the content was created.
              format: date-time
            updatedAt:
              type: string
              description: The last time the content was updated.
              format: date-time
            author:
              type: string
              description: The id of the content's author.
            votes:
              type: array
              description: List of votes made on the content.
              items:
                type: string
                description: The id of the vote in the list.
            comments:
              type: array
              description: List of comments made on a content.
              items:
                type: string
                description: The id of the comment in the list.
            reports:
              type: array
              description: List of reports made on the content.
              items:
                type: string
                description: The id of the report in the list.

    Post:
      allOf:
        - $ref: '#/components/schemas/Content'
        - type: object
          description: A Postcrunch post.
          properties:
            title:
              type: string
              description: The title of the post.

    Comment:
      allOf:
        - $ref: '#/components/schemas/Content'
        - type: object
          description: A comment made on a content.
          properties:
            target:
              type: string
              description: The id of the targeted content.

    Vote:
      type: object
      description: A vote made on a post.
      required:
        - author
        - target
      properties:
        id:
          type: string
          description: The vote's id.
        voteType:
          type: string
          description: The type of the vote.
          enum:
            - UP
            - DOWN
        createdAt:
          type: string
          description: The time the voted was created.
          format: date-time
        author:
          type: string
          description: The id of the vote's author.
        target:
          type: string
          description: The id of the vote's targeted content.

    Report:
      type: object
      description: A report made on a post or comment.
      required:
        - author
        - target
      properties:
        id:
          type: string
          description: The report's id.
        reason:
          type: string
          description: The reason for reporting the content.
          enum:
            - SPAM
            - FRAUD
            - INAPPROPRIATE
            - OTHER
        createdAt:
          type: string
          description: The time the report was created.
          format: date-time
        author:
          type: string
          description: The id of the report's author.
        target:
          type: string
          description: The id of the report's targeted content.

    ErrorResponse:
      type: object
      description: The response of an invalid HTTP request.
      properties:
        message:
          type: string
          description: A human-readable message describing the error.
        code:
          type: integer
          description: The HTTP status code.
          format: int32