openapi: 3.1.0

info:
  title: Postcrunch
  description: 'A social media platform where we crunch others post and share ours.'
  version: 1.0.0
  contact:
    name: Nguyen Pham
    email: nguyenminhpham24@gmail.com

servers:
  - url: https://github.com/nguyepham
    description: Development server

tags:
  - name: user
    description: Sign up, sign in, Edit profile.
  - name: newsfeed
    description: CRUD operations with the newsfeed.
  - name: post
    description: CRUD operations with a post.
  - name: comment
    description: CRUD operations with a comment.

paths:
  /home:
    get:
      operationId: fetchDemo
      responses:
        200:
          content:
            application/json:
              schema:
                type: string

  /api/v1/newsfeed:
    get:
      tags:
        - newsfeed
      description: Fetch the Postcrunch newsfeed.
      operationId: getNewsfeed
      responses:
        200:
          description: Fetched successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Newsfeed'
            application/xml:
              schema:
                $ref: '#/components/schemas/Newsfeed'

components:
  schemas:
    User:
      description: A Postcrunch user.
      type: object
      required:
        - username
        - password
      properties:
        username:
          description: The account's username used as the default display name.
          type: string
        name:
          description: The display name of the user.
          type: string
        password:
          description: The account's password.
          type: string
        email:
          description: The user's email.
          type: string
          format: email
        dateOfBirth:
          description: The user's birthday.
          type: string
          format: date-time
        gender:
          description: The user's gender.
          type: string

    Newsfeed:
      description: The Postcrunch newsfeed.
      type: object
      properties:
        lastFetched:
          description: The last time the newsfeed was fetched.
          type: string
          format: date-time
        posts:
          description: The list of posts on the newsfeed.
          type: array
          items:
            $ref: '#/components/schemas/Post'

    Content:
      description: A content on the newsfeed (post or comment).
      type: object
      properties:
        id:
          description: The comment's id.
          type: string
        isAPost:
          description: Whether this content is a post or not.
          type: boolean
        addedTIme:
          description: The time the content was added.
          type: string
          format: date-time
        author:
          description: The user who created the content.
          $ref: '#/components/schemas/User'
        votes:
          description: List of up/down votes made on the content.
          type: array
          items:
            $ref: '#/components/schemas/Vote'
        text:
          description: The text in the content.
          type: string

    Post:
      allOf:
        - $ref: '#/components/schemas/Content'
        - description: A Postcrunch post.
          type: object
          properties:
            comments:
              description: List of comments made on the post.
              type: array
              items:
                $ref: '#/components/schemas/Comment'

    Comment:
      allOf:
        - $ref: '#/components/schemas/Content'
        - description: A comment made on a post.
          type: object
          properties:
            target:
              description: The target post of the comment.
              $ref: '#/components/schemas/Post'

    Vote:
      description: A vote made on a post.
      type: object
      properties:
        isUpVote:
          description: Whether a vote is up vote or not.
          type: boolean
        addedTIme:
          description: The time the voted was created.
          type: string
          format: date-time

    Report:
      description: A report made on a post or comment.
      type: object
      properties:
        isUpVote:
          description: Whether a vote is up vote or not.
          type: boolean
        addedTIme:
          description: The time the report was created.
          type: string
          format: date-time
        target:
          description: The content which was reported.
          $ref: '#/components/schemas/Content'
